### ISSUE TITLE
Terraform plugin throws version error with op CLI

### ISSUE THREAD

**Issue by herda05** [1Password/terraform-provider-onepassword#147]
### Your environment
Terraform Provider Version: 1.4.1
Connect Server Version: n/a
CLI Version: 2.23.0-beta.01
OS: MacOS Ventura 13.4.1
Terraform Version: 1.6.4

## What happened?
run a terraform plan and recieve the following error:

Error: failed to get version of op CLI: Version segment starts with 0 (input is: 2.23.0-beta.01)

## What did you expect to happen?
The main.tf:
provider "onepassword" {
  account     = XXXXXXXXXXXXXXXXXXXXXX
  op_cli_path = "/usr/local/bin/op"
}

data "onepassword_item" "ans_pub_key" {
  vault = XXXXXXXXXXXXXXXXXX
  title = "ansadmin_dev_key"
}

output "one_pass" {
  value = data.onepassword_item.ans_pub_key
}

## Steps to reproduce
1. Create main.tf with the above code.
2. execute terraform plan  in the same directory

## Notes & Logs
I can run the op command just fine. I needed to upgrade the op client to get the terraform plugin.

**Comment by volodymyrZotov** [comment]
@herda05 Hi. The problem is that you used a beta version. As per [semantic versioniong](https://semver.org/#spec-item-11),   the beta version is considered less than prod version aka `v2.23.0-beta01 < v2.23.0`. The provider is required to use version `>=v2.23.0`.

So, to use it, either install cli `v2.23.0` or the next stable `v2.24.0`.
