### ISSUE TITLE
List vault items

### ISSUE THREAD

**Issue by nikaro** [1Password/terraform-provider-onepassword#73]
### Summary

Would be nice to get an `items` list when accessing `data.onepassword_vault`.

### Use cases

I want to use a dedicated and shared vault to store and manage applications secrets. Then i would do something like this to create the secrets into my provider secret manager:

```tf
data "onepassword_vault" "secrets" {
  name = "My Vault"
}

data "onepassword_item" "secrets" {
  for_each = data.onepassword_vault.secrets.items
  vault    = data.onepassword_vault.secrets.id
  uuid     = each.key
}

resource "myprovider_secret_manager" "secrets" {
  for_each = data.onepassword_vault.secrets.items
  name     = data.onepassword_item[each.key].password.key
  value    = data.onepassword_item[each.key].password.value
}
```

### Is there a workaround to accomplish this today?

The current workaround would be to use one big item with each secret as a password field.

**Comment by caimeq** [comment]
I see you closed this issue @nikaro Was this because it was resolved in a release? 
I am not seeing this in the code or release notes. 
Did you find a way to accomplish this outside of the provider with workaround?

This is definitely a useful request and I am unclear if this was considered. 

Apologies for dragging up an old issue.

**Comment by nikaro** [comment]
I don't recall exactly, but i think i found my way around, and then i didn't have the need anymore. So i closed it to avoid leaving a stale issue here.
